---
- name: Generate the npm directory path
  set_fact:
    _npm_dir: "\
      {{ _run_temp_dir.path }}/src\
      {% if pantheon_deploy.build.npm_dir is defined %}\
      /{{ pantheon_deploy.build.npm_dir }}\
      {% endif %}"

- name: Check if package.json exists
  stat:
    name: "{{ _npm_dir }}/package.json"
  register: _package_json

- name: Install NPM
  shell: "npm {{ pantheon_deploy.build.npm_install_cmd | default('ci') }}"
  args:
    chdir: "{{ _npm_dir }}"
  when:
    - _package_json.stat.exists == true

- name: Run npm build
  shell: "npm run {{ pantheon_deploy.build.npm_build_script_name | default('build') }}"
  args:
    chdir: "{{ _npm_dir }}"
  when:
    - _package_json.stat.exists == true
  
- name: Copy changes to source
  ansible.posix.synchronize:
    src: "{{ _run_temp_dir.path }}/src/"
    dest: "{{ pantheon_deploy.source.git_dir }}/"
    delete: no
    archive: yes
    rsync_opts: "--exclude=.git/"
  delegate_to: localhost
  when:
    - pantheon_deploy.build.copy == true