---
- name: Create directories for secrets
  file:
    dest: "{{ _run_dir }}/src/{{ item.path | dirname }}"
    state: directory
  loop: "{{ pantheon_deploy.secrets | default([]) }}"
- name: Write secrets
  copy:
    dest: "{{ _run_dir.path }}/src/{{ item.path }}"
    content: "{{ item.value }}"
  loop: "{{ pantheon_deploy.secrets | default([]) }}"

